## Setup machine
version: 1.0
machine:
  java:
    version: 'oraclejdk8'
  node:
    version: v8.9.0
  ruby:
    version: 2.1.2
  environment:
    ANDROID_HOME: /usr/local/android-sdk-linux


## Setup dependencies
dependencies:
  override:
    - npm install

  pre:
    - npm install -g ionic cordova
    - echo y | android update sdk --no-ui --all --filter tools,platform-tools,extra-google-m2repository,extra-google-google_play_services,extra-android-support,extra-android-m2repository,android-25
    - echo y | android update sdk --no-ui --all --filter build-tools-25.0.0

  cache_directories:
    - /usr/local/android-sdk-linux/tools
    - /usr/local/android-sdk-linux/build-tools/24.0.1

  post:
    - mkdir www
    - ionic cordova platform add android -Y --noresources

test:
  pre:
    - npm install

  override:
    - ionic cordova build android -Y
    - cp -r platforms/android/build/outputs/apk $CIRCLE_ARTIFACTS
    - mocha test --reporter mocha-junit-reporter:
        environment:
          MOCHA_FILE: $CIRCLE_TEST_REPORTS/junit/test-results.xml